import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { activeRegistry } from "../cli/registry.js";
import { coreModules } from "../modules/index.js";
import { coreIntegrations } from "../modules/integrations.js";
import type { RoworkConfig } from "../plugins/api.js";

export const AGENTS_FILE = "AGENTS.md";
export const CLAUDE_FILE = "CLAUDE.md";

const BEGIN = "<!-- rowork:begin: generated by Rowork and rewritten by `rowork add`. Put your own notes OUTSIDE this block. -->";
const END = "<!-- rowork:end -->";

/**
 * The block Rowork owns in AGENTS.md.
 *
 * Built from live data (the registered commands, the installed modules) so it
 * cannot drift from what the project really offers. It is written for two
 * readers at once: a person learning the project, and an AI about to change it.
 */
export function renderManagedSection(config: RoworkConfig, roworkVersion: string): string {
	const installed = config.modules ?? [];
	const commands = (activeRegistry()?.all() ?? [])
		.map((entry) => entry.definition)
		.filter((definition) => !["console", "help"].includes(definition.name));

	const lines: string[] = [
		BEGIN,
		`## ${config.name}: a Rowork project`,
		"",
		`Generated by Rowork ${roworkVersion}. roblox-ts (TypeScript compiled to Luau) + Flamework (services, controllers, components, dependency injection) + Rojo (sync into Roblox Studio).`,
		"",
		"### How to work here",
		"",
		"- **Create things with Rowork instead of writing the files by hand.** It names them, puts them in the right directory and registers them with Flamework (a class in a directory not passed to `Flamework.addPaths` compiles and then silently never runs).",
		"- **Always pass every argument.** Without arguments a command opens interactive questions and waits for a terminal. Commands marked *guided* below do that.",
		"- **Modules connect themselves.** When two installed modules work together, `rowork add` generates the glue (see \"Modules wired together\"); `rowork wire` retries it. Do not write that glue by hand.",
		"- **Know what exists first:** `rowork info --json` prints the project, the installed modules and every command with its options, as JSON.",
		"- **Check your work:** `npm run build` (or `npx rbxtsc`) must finish with no error. In Studio, `rowork dev -d` runs everything in the background, `rowork dev:logs` shows compiler errors, `rowork dev:stop` stops it.",
		"- Files starting with `// Generated by` are rewritten by Rowork: do not edit them.",
		"- Never edit `node_modules/`, `out/`, `include/` or `sourcemap.json`. They are build output.",
		"",
		"### Layout",
		"",
		`- \`${config.paths.services}/\`: Flamework services (server logic). \`${config.paths.controllers}/\`: controllers (client logic). \`${config.paths.shared}/\`: code shared by both.`,
		`- \`${config.paths.source}/server/runtime.server.ts\` and \`${config.paths.source}/client/runtime.client.ts\`: entry points listing the directories Flamework scans.`,
		"- `default.project.json`: what appears in Studio. `rokit.toml`: pinned Rojo version. `rowork.json`: Rowork's own configuration.",
		"",
		"### Installed modules",
		"",
	];

	if (installed.length === 0) {
		lines.push("None yet. `rowork add` lists what can be added (player data, leaderstats, typed networking...).", "");
	} else {
		for (const name of installed) {
			const module = coreModules.find((candidate) => candidate.name === name);
			lines.push(`#### ${module?.title ?? name} (\`${name}\`)`, "");
			if (module?.agentGuide === undefined) lines.push("Installed with `rowork add`. Read its files.");
			else for (const line of module.agentGuide) lines.push(`- ${line}`);
			lines.push("");
		}
	}

	const wired = coreIntegrations.filter((integration) => (config.integrations ?? []).includes(integration.name));
	if (wired.length > 0) {
		lines.push("### Modules wired together", "", "Rowork generated this glue because the modules below are both installed. Use it instead of writing it again.", "");
		for (const integration of wired) {
			lines.push(`#### ${integration.title} (\`${integration.modules.join(" + ")}\`)`, "");
			for (const line of integration.agentGuide ?? [integration.description]) lines.push(`- ${line}`);
			lines.push("");
		}
	}

	const available = coreModules.filter((module) => !installed.includes(module.name));
	if (available.length > 0) {
		lines.push("### Modules you can still add", "");
		for (const module of available) {
			const needs = module.requires === undefined ? "" : ` (needs: ${module.requires.join(", ")})`;
			lines.push(`- \`rowork add:${module.name}\`: ${module.description}${needs}`);
		}
		lines.push("");
	}

	lines.push("### Commands", "");
	for (const command of commands) {
		const guided = command.guided === true ? " *(guided: pass all arguments)*" : "";
		lines.push(`- \`rowork ${command.name}\`${guided}: ${command.description}`);
	}
	lines.push("", "Every command has `--help`. Use `rowork info --json` for the full option list.", END);
	return `${lines.join("\n")}\n`;
}

/**
 * Creates or refreshes AGENTS.md (and a CLAUDE.md that points to it).
 *
 * Only the block between the markers is rewritten: anything the user wrote
 * around it stays. An existing CLAUDE.md is never touched. Claude Code reads
 * CLAUDE.md and most other agents read AGENTS.md, so one file holds the content
 * and the other imports it.
 */
export function syncAgentDocs(projectRoot: string, config: RoworkConfig, roworkVersion: string): string[] {
	const touched: string[] = [];
	const section = renderManagedSection(config, roworkVersion);
	const agentsPath = join(projectRoot, AGENTS_FILE);

	if (!existsSync(agentsPath)) {
		writeFileSync(agentsPath, `# ${config.name}\n\n${section}`, "utf8");
		touched.push(AGENTS_FILE);
	} else {
		const current = readFileSync(agentsPath, "utf8");
		const start = current.indexOf("<!-- rowork:begin");
		const end = current.indexOf(END);
		const next =
			start !== -1 && end > start
				? `${current.slice(0, start)}${section.trimEnd()}${current.slice(end + END.length)}`
				: `${current.trimEnd()}\n\n${section}`;
		if (next !== current) {
			writeFileSync(agentsPath, next, "utf8");
			touched.push(AGENTS_FILE);
		}
	}

	const claudePath = join(projectRoot, CLAUDE_FILE);
	if (!existsSync(claudePath)) {
		writeFileSync(claudePath, "@AGENTS.md\n", "utf8");
		touched.push(CLAUDE_FILE);
	}
	return touched;
}

/** Removes the Rowork block when leaving Rowork; deletes files that held nothing else. */
export function removeAgentDocs(projectRoot: string): string[] {
	const touched: string[] = [];
	const agentsPath = join(projectRoot, AGENTS_FILE);

	if (existsSync(agentsPath)) {
		const current = readFileSync(agentsPath, "utf8");
		const start = current.indexOf("<!-- rowork:begin");
		const end = current.indexOf(END);
		if (start !== -1 && end > start) {
			const rest = `${current.slice(0, start)}${current.slice(end + END.length)}`;
			// A file that only held the generated title and block held nothing of the user's.
			const remaining = rest.replace(/^# .*$/m, "").trim();
			if (remaining === "") rmSync(agentsPath);
			else writeFileSync(agentsPath, `${rest.trim()}\n`, "utf8");
			touched.push(AGENTS_FILE);
		}
	}

	const claudePath = join(projectRoot, CLAUDE_FILE);
	if (existsSync(claudePath) && readFileSync(claudePath, "utf8").trim() === "@AGENTS.md" && !existsSync(agentsPath)) {
		rmSync(claudePath);
		touched.push(CLAUDE_FILE);
	}
	return touched;
}
